version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "8000"
    environment:
      DATABASE_URL: postgresql://appuser:NYHgt7HiDizBL1QJaA5WTzD76W8fqLay@dpg-d10qtere5dus73ak0j60-a.oregon-postgres.render.com/mnemoscheme4
      FLASK_APP: app:create_app()
    restart: on-failure